version: '2'
services:
    apache:
        image: httpd:2.2
        build:
            context: .
            dockerfile: Dockerfile.apache
        ports:
            - "80:80"
        depends_on:
            - php
        environment:
            - "MYSQL_PASSWORD=sPes4uBrEcHUq5qE"
    php:
        image: php:5.6.32
        build:
            context: .
            dockerfile: Dockerfile.php
        depends_on:
            - mysql
    mysql:
        image: mysql:5.6
        volumes:
            - mysql-data:/var/lib/mysql
        command: ['mysqld', '--character-set-server=utf8']
        environment:
            - "MYSQL_ROOT_PASSWORD=sPes4uBrEcHUq5qE"
            - "TZ=Asia/Taipei"

volumes:
    mysql-data: