version: '2'
services:
    apache:
        image: php:5.6-apache
        ports:
            - "${APACHE_HOST_HTTP_PORT}:80"
            - "${APACHE_HOST_HTTPS_PORT}:443"
        depends_on:
            - mysql
        volumes:
            - ${APACHE_WWW_PATH}:/var/www/html
            - ${APACHE_HOST_LOG_PATH}:/var/log/apache2


    mysql:
        image: mysql:5.6

        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - mysql-data:/var/lib/mysql
            - ${MYSQL_LOG_PATH}:/var/log/mysql
        command: ['mysqld', '--character-set-server=utf8']
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - TZ=Asia/Taipei

volumes:
    mysql-data: