version: '3.3'
services:
    web-server:
        image: nginx:alpine
        restart: always
        container_name: nginx
        depends_on:
            - mariadb
            - php-fpm
        volumes:
            - ${APACHE_WWW_PATH}:/var/www/html
            - ${APACHE_PMA_PATH}:/var/www/html/pma
            - ./www/vendor/:/var/www/vendor/
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./log/nginx/:/var/log/nginx/
            - ./conf/nginx/sites/default.conf:/etc/nginx/conf.d/default.conf
            - run_vol:/var/run
        ports:
            - "${APACHE_HOST_HTTP_PORT}:80"
            - "${APACHE_HOST_HTTPS_PORT}:443"
        # networks:
        #     - elk_net
        #     - default

    php-fpm:
        image: andygott/php-fpm-alpine-imagick
        restart: always
        container_name: php-fpm
        depends_on:
            - mariadb
        links:
            - mariadb
        volumes:
            - ${APACHE_WWW_PATH}:/var/www/html
            - ${APACHE_PMA_PATH}:/var/www/html/pma
            - ${MYSQL_DATA_PATH}:/var/lib/mysql
            - ./www/vendor/:/var/www/vendor/
            - ./conf/php/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/php-ini-overrides.ini
            - ./conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        working_dir: /var/www/html

    # apache:
    #     build: .
    #     ports:
    #         - "${APACHE_HOST_HTTP_PORT}:80"
    #         - "${APACHE_HOST_HTTPS_PORT}:443"
    #     depends_on:
    #         - mysql
    #     volumes:
    #         - ${APACHE_WWW_PATH}:/var/www/html
    #         - ${APACHE_HOST_LOG_PATH}:/var/log/apache2
    #         - ${APACHE_CONF_PATH}:/etc/apache2/custom-conf
    #         - ${PHP_CONF_PATH}:/usr/local/etc/php/conf.d

    mariadb:
        image: mariadb:10
        container_name: mariadb
        restart: always
        ports:
            - "${MYSQL_PORT}:3306"
        # networks:
        #     - elk_net
        #     - default
        volumes:
            - ${MYSQL_DATA_PATH}:/var/lib/mysql
            - ${MYSQL_LOG_PATH}:/var/log/mysql
            - ${MYSQL_CONF_PATH}my.cnf:/etc/mysql/conf.d/settings.cnf
            - ${MYSQL_CONF_PATH}docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        command: ['mysqld', '--character-set-server=utf8']
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - TZ=Asia/Taipei
    redis:
        image: redis:latest
        container_name: redis
volumes:
    run_vol:
        driver_opts:
            type: tmpfs
            device: tmpfs
# networks:
#     elk_net:
#         external:
#             name: elk
