version: '3.3'
services:
    web-server:
        image: nginx:alpine
        restart: unless-stopped
        container_name: nginx_fc
        depends_on:
            - mariadb
            - php-fpm
        volumes:
            - ${APACHE_WWW_PATH}:/var/www
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./conf/nginx/letsencrypt:/etc/nginx/letsencrypt
            - ./log/nginx/:/var/log/nginx/
            - ./conf/nginx/sites/default.conf:/etc/nginx/conf.d/default.conf
            - run_vol:/var/run
        ports:
            - "${APACHE_HOST_HTTP_PORT}:80"
            - "${APACHE_HOST_HTTPS_PORT}:443"
        working_dir: /var/www

    php-fpm:
        build: .
        image: php_fc:191028
        restart: unless-stopped
        container_name: php-fpm_fc
        depends_on:
            - mariadb
        links:
            - mariadb
        volumes:
            - ${APACHE_WWW_PATH}:/var/www
            - ${MYSQL_DATA_PATH}:/var/lib/mysql
            - ./conf/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
            - ./conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        working_dir: /var/www

    mariadb:
        image: mariadb:10.4.6
        container_name: mariadb_fc
        restart: unless-stopped
        ports:
            - "${MYSQL_PORT}:3306"
        # networks:
        #     - elk_net
        #     - default
        volumes:
            - ${MYSQL_DATA_PATH}:/var/lib/mysql
            - ${MYSQL_LOG_PATH}:/var/log/mysql
            - ${MYSQL_CONF_PATH}my.cnf:/etc/mysql/conf.d/settings.cnf
            - ${MYSQL_CONF_PATH}docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        command: ['mysqld', '--character-set-server=utf8']
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - TZ=Asia/Taipei

    redis:
        image: redis:latest
        container_name: redis_fc
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - ./../redis/redis.conf:/usr/local/etc/redis.conf
            - ./../../redis/data:/usr/local/redis/data
            - ./../../redis/redis.log:/usr/local/redis/redis.log
volumes:
    run_vol:
        driver_opts:
            type: tmpfs
            device: tmpfs

