-- 2026-05-01 daily SQL delivery
-- Add schema changes and DBA-executed full-table SQL for this date in this file.

CREATE TABLE IF NOT EXISTS `tbl_doorman_blacklist` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `match_type` enum('exact','contains') NOT NULL DEFAULT 'exact',
  `keyword` varchar(191) NOT NULL DEFAULT '',
  `status` enum('Enabled','Disabled') NOT NULL DEFAULT 'Enabled',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `last_ts` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `last_user` int(11) DEFAULT 0,
  `insert_ts` timestamp NULL DEFAULT current_timestamp(),
  `insert_user` int(11) DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_match_keyword` (`match_type`,`keyword`),
  KEY `idx_status_match_type` (`status`,`match_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Weak password blacklist for Doorman checks';

INSERT INTO `tbl_doorman_blacklist` (`match_type`, `keyword`, `status`, `remark`)
VALUES
  ('exact', '123456', 'Enabled', 'Common weak password'),
  ('exact', '1234567', 'Enabled', 'Common weak password'),
  ('exact', '12345678', 'Enabled', 'Common weak password'),
  ('exact', '123456789', 'Enabled', 'Common weak password'),
  ('exact', '1234567890', 'Enabled', 'Common weak password'),
  ('exact', '123123', 'Enabled', 'Common weak password'),
  ('exact', '123321', 'Enabled', 'Common weak password'),
  ('exact', '123qwe', 'Enabled', 'Keyboard pattern'),
  ('exact', '123qweasd', 'Enabled', 'Keyboard pattern'),
  ('exact', '1234qwer', 'Enabled', 'Keyboard pattern'),
  ('exact', '654321', 'Enabled', 'Common weak password'),
  ('exact', '987654321', 'Enabled', 'Common weak password'),
  ('exact', '111111', 'Enabled', 'Common weak password'),
  ('exact', '11111111', 'Enabled', 'Common weak password'),
  ('exact', '222222', 'Enabled', 'Common weak password'),
  ('exact', '333333', 'Enabled', 'Common weak password'),
  ('exact', '444444', 'Enabled', 'Common weak password'),
  ('exact', '555555', 'Enabled', 'Common weak password'),
  ('exact', '666666', 'Enabled', 'Common weak password'),
  ('exact', '777777', 'Enabled', 'Common weak password'),
  ('exact', '888888', 'Enabled', 'Common weak password'),
  ('exact', '999999', 'Enabled', 'Common weak password'),
  ('exact', '000000', 'Enabled', 'Common weak password'),
  ('exact', '00000000', 'Enabled', 'Common weak password'),
  ('exact', '121212', 'Enabled', 'Common weak password'),
  ('exact', '112233', 'Enabled', 'Common weak password'),
  ('exact', '5201314', 'Enabled', 'Common weak password'),
  ('exact', '1314520', 'Enabled', 'Common weak password'),
  ('exact', 'abc123', 'Enabled', 'Common weak password'),
  ('exact', 'abc123456', 'Enabled', 'Common weak password'),
  ('exact', 'abcd1234', 'Enabled', 'Common weak password'),
  ('exact', 'qwerty', 'Enabled', 'Common weak password'),
  ('exact', 'qwerty1', 'Enabled', 'Common weak password'),
  ('exact', 'qwerty12', 'Enabled', 'Common weak password'),
  ('exact', 'qwerty123', 'Enabled', 'Common weak password'),
  ('exact', 'qwerty12345', 'Enabled', 'Common weak password'),
  ('exact', 'qwertyuiop', 'Enabled', 'Common weak password'),
  ('exact', 'asdfgh', 'Enabled', 'Keyboard pattern'),
  ('exact', 'asdf1234', 'Enabled', 'Keyboard pattern'),
  ('exact', 'asdfghjkl', 'Enabled', 'Keyboard pattern'),
  ('exact', 'zxcvbn', 'Enabled', 'Keyboard pattern'),
  ('exact', 'zxcvbnm', 'Enabled', 'Keyboard pattern'),
  ('exact', 'password', 'Enabled', 'Common weak password'),
  ('exact', 'password1', 'Enabled', 'Common weak password'),
  ('exact', 'password12', 'Enabled', 'Common weak password'),
  ('exact', 'password123', 'Enabled', 'Common weak password'),
  ('exact', 'password1234', 'Enabled', 'Common weak password'),
  ('exact', 'password12345', 'Enabled', 'Common weak password'),
  ('exact', 'password123456', 'Enabled', 'Common weak password'),
  ('exact', 'passw0rd', 'Enabled', 'Common weak password'),
  ('exact', 'p@ssword', 'Enabled', 'Common weak password'),
  ('exact', 'p@ssw0rd', 'Enabled', 'Common weak password'),
  ('exact', 'welcome', 'Enabled', 'Common weak password'),
  ('exact', 'welcome1', 'Enabled', 'Common weak password'),
  ('exact', 'welcome123', 'Enabled', 'Common weak password'),
  ('exact', 'letmein', 'Enabled', 'Common weak password'),
  ('exact', 'letmein123', 'Enabled', 'Common weak password'),
  ('exact', 'iloveyou', 'Enabled', 'Common weak password'),
  ('exact', '1q2w3e4r', 'Enabled', 'Common weak password'),
  ('exact', '1qaz2wsx', 'Enabled', 'Keyboard pattern'),
  ('exact', '1qazxsw2', 'Enabled', 'Keyboard pattern'),
  ('exact', 'zaq12wsx', 'Enabled', 'Common weak password'),
  ('exact', 'zaq1zaq1', 'Enabled', 'Keyboard pattern'),
  ('exact', 'qazwsx', 'Enabled', 'Keyboard pattern'),
  ('exact', 'admin', 'Enabled', 'Common weak password'),
  ('exact', 'admin1', 'Enabled', 'Default credential'),
  ('exact', 'admin12', 'Enabled', 'Default credential'),
  ('exact', 'admin123', 'Enabled', 'Common weak password'),
  ('exact', 'admin1234', 'Enabled', 'Default credential'),
  ('exact', 'administrator', 'Enabled', 'Default credential'),
  ('exact', 'root', 'Enabled', 'Default credential'),
  ('exact', 'root123', 'Enabled', 'Default credential'),
  ('exact', 'rootroot', 'Enabled', 'Default credential'),
  ('exact', 'guest', 'Enabled', 'Default credential'),
  ('exact', 'guest123', 'Enabled', 'Default credential'),
  ('exact', 'test', 'Enabled', 'Default credential'),
  ('exact', 'test123', 'Enabled', 'Default credential'),
  ('exact', 'demo', 'Enabled', 'Default credential'),
  ('exact', 'demo123', 'Enabled', 'Default credential'),
  ('exact', 'login', 'Enabled', 'Default credential'),
  ('exact', 'login123', 'Enabled', 'Default credential'),
  ('exact', 'default', 'Enabled', 'Default credential'),
  ('exact', 'changeme', 'Enabled', 'Default credential'),
  ('exact', 'secret', 'Enabled', 'Common weak password'),
  ('exact', 'secret123', 'Enabled', 'Common weak password'),
  ('exact', 'master', 'Enabled', 'Common weak password'),
  ('exact', 'master123', 'Enabled', 'Common weak password'),
  ('exact', 'superuser', 'Enabled', 'Default credential'),
  ('exact', 'service', 'Enabled', 'Default credential'),
  ('exact', 'service123', 'Enabled', 'Default credential'),
  ('exact', 'system', 'Enabled', 'Default credential'),
  ('exact', 'system123', 'Enabled', 'Default credential'),
  ('exact', 'manager', 'Enabled', 'Default credential'),
  ('exact', 'manager123', 'Enabled', 'Default credential'),
  ('exact', 'user', 'Enabled', 'Default credential'),
  ('exact', 'user123', 'Enabled', 'Default credential'),
  ('exact', 'user1234', 'Enabled', 'Default credential'),
  ('exact', 'member', 'Enabled', 'Default credential'),
  ('exact', 'member123', 'Enabled', 'Default credential'),
  ('exact', 'staff', 'Enabled', 'Default credential'),
  ('exact', 'staff123', 'Enabled', 'Default credential'),
  ('exact', 'office', 'Enabled', 'Default credential'),
  ('exact', 'office123', 'Enabled', 'Default credential'),
  ('exact', 'company', 'Enabled', 'Default credential'),
  ('exact', 'company123', 'Enabled', 'Default credential'),
  ('exact', 'team', 'Enabled', 'Default credential'),
  ('exact', 'team123', 'Enabled', 'Default credential'),
  ('exact', 'hello', 'Enabled', 'Common weak password'),
  ('exact', 'hello123', 'Enabled', 'Common weak password'),
  ('exact', 'dragon', 'Enabled', 'Common weak password'),
  ('exact', 'monkey', 'Enabled', 'Common weak password'),
  ('exact', 'baseball', 'Enabled', 'Common weak password'),
  ('exact', 'football', 'Enabled', 'Common weak password'),
  ('exact', 'soccer', 'Enabled', 'Common weak password'),
  ('exact', 'starwars', 'Enabled', 'Common weak password'),
  ('exact', 'freedom', 'Enabled', 'Common weak password'),
  ('exact', 'whatever', 'Enabled', 'Common weak password'),
  ('exact', 'trustno1', 'Enabled', 'Common weak password'),
  ('exact', 'princess', 'Enabled', 'Common weak password'),
  ('exact', 'sunshine', 'Enabled', 'Common weak password'),
  ('exact', 'lovely', 'Enabled', 'Common weak password'),
  ('exact', 'flower', 'Enabled', 'Common weak password'),
  ('exact', 'kitty', 'Enabled', 'Common weak password'),
  ('exact', 'google', 'Enabled', 'Brand-like weak password'),
  ('exact', 'google123', 'Enabled', 'Brand-like weak password'),
  ('exact', 'apple', 'Enabled', 'Brand-like weak password'),
  ('exact', 'apple123', 'Enabled', 'Brand-like weak password'),
  ('exact', 'windows', 'Enabled', 'Brand-like weak password'),
  ('exact', 'windows123', 'Enabled', 'Brand-like weak password'),
  ('exact', 'android', 'Enabled', 'Brand-like weak password'),
  ('exact', 'android123', 'Enabled', 'Brand-like weak password'),
  ('exact', 'iphone', 'Enabled', 'Brand-like weak password'),
  ('exact', 'iphone123', 'Enabled', 'Brand-like weak password'),
  ('exact', 'samsung', 'Enabled', 'Brand-like weak password'),
  ('exact', 'taiwan', 'Enabled', 'Locale weak password'),
  ('exact', 'taipei', 'Enabled', 'Locale weak password'),
  ('exact', 'happy', 'Enabled', 'Common weak password'),
  ('exact', 'newyear2024', 'Enabled', 'Seasonal weak password'),
  ('exact', 'newyear2025', 'Enabled', 'Seasonal weak password'),
  ('exact', 'spring2024', 'Enabled', 'Seasonal weak password'),
  ('exact', 'spring2025', 'Enabled', 'Seasonal weak password'),
  ('exact', 'summer2024', 'Enabled', 'Seasonal weak password'),
  ('exact', 'summer2025', 'Enabled', 'Seasonal weak password'),
  ('exact', 'autumn2024', 'Enabled', 'Seasonal weak password'),
  ('exact', 'autumn2025', 'Enabled', 'Seasonal weak password'),
  ('exact', 'winter2024', 'Enabled', 'Seasonal weak password'),
  ('exact', 'winter2025', 'Enabled', 'Seasonal weak password'),
  ('contains', 'password', 'Enabled', 'Contains common weak keyword'),
  ('contains', 'passw0rd', 'Enabled', 'Contains common weak keyword'),
  ('contains', 'qwerty', 'Enabled', 'Contains common weak keyword'),
  ('contains', 'asdf', 'Enabled', 'Contains keyboard pattern'),
  ('contains', 'zxcv', 'Enabled', 'Contains keyboard pattern'),
  ('contains', 'qazwsx', 'Enabled', 'Contains keyboard pattern'),
  ('contains', '123456', 'Enabled', 'Contains common number sequence'),
  ('contains', '654321', 'Enabled', 'Contains common number sequence'),
  ('contains', '111111', 'Enabled', 'Contains repeated number sequence'),
  ('contains', '000000', 'Enabled', 'Contains repeated number sequence'),
  ('contains', 'abc123', 'Enabled', 'Contains common weak keyword'),
  ('contains', 'admin', 'Enabled', 'Contains default credential keyword'),
  ('contains', 'root', 'Enabled', 'Contains default credential keyword'),
  ('contains', 'guest', 'Enabled', 'Contains default credential keyword'),
  ('contains', 'test', 'Enabled', 'Contains default credential keyword'),
  ('contains', 'demo', 'Enabled', 'Contains default credential keyword'),
  ('contains', 'welcome', 'Enabled', 'Contains common weak keyword'),
  ('contains', 'letmein', 'Enabled', 'Contains common weak keyword'),
  ('contains', 'changeme', 'Enabled', 'Contains default credential keyword'),
  ('contains', 'default', 'Enabled', 'Contains default credential keyword'),
  ('contains', 'secret', 'Enabled', 'Contains common weak keyword'),
  ('contains', 'service', 'Enabled', 'Contains common weak keyword'),
  ('contains', 'system', 'Enabled', 'Contains common weak keyword'),
  ('contains', 'manager', 'Enabled', 'Contains common weak keyword'),
  ('contains', 'staff', 'Enabled', 'Contains common weak keyword'),
  ('contains', 'member', 'Enabled', 'Contains common weak keyword'),
  ('contains', 'office', 'Enabled', 'Contains common weak keyword'),
  ('contains', 'company', 'Enabled', 'Contains common weak keyword'),
  ('contains', 'team', 'Enabled', 'Contains common weak keyword'),
  ('contains', 'newyear', 'Enabled', 'Contains seasonal keyword'),
  ('contains', 'spring', 'Enabled', 'Contains seasonal keyword'),
  ('contains', 'summer', 'Enabled', 'Contains seasonal keyword'),
  ('contains', 'autumn', 'Enabled', 'Contains seasonal keyword'),
  ('contains', 'winter', 'Enabled', 'Contains seasonal keyword')
ON DUPLICATE KEY UPDATE
  `status` = VALUES(`status`),
  `remark` = VALUES(`remark`),
  `last_ts` = current_timestamp(),
  `last_user` = VALUES(`last_user`);